---
driver_plugin: vagrant
driver_config:
  customize:
    cpus: 1
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.16.42
  log_level: info
  log_file: /var/log/chef-solo.log

platforms:
- name: centos-7.2
  driver_config:
    box: bento/centos-7.2
- name: centos-6.8
  driver_config:
    box: bento/centos-6.8
- name: ubuntu-12.04
  driver_config:
    box: bento/ubuntu-12.04
- name: ubuntu-14.04
  driver_config:
    box: bento/ubuntu-14.04

suites:
- name: default
  run_list: ['recipe[apt]','recipe[rs-storage]']
  attributes:
    apt:
      compile_time_update: true
