---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.18'

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
- name: centos-6.8
  driver_config:
    box: opscode-centos-6.8
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.8_provisionerless.box
suites:
- name: default
  run_list: ["recipe[rs-storage]"]
  attributes: {}
